### ISSUE TITLE
Ice fails in public network

### ISSUE THREAD

**Issue by atz3n** [xem/miniWebRTC#2]
Hello!

I found your project while trying to get the [serverless-webrtc](https://github.com/cjb/serverless-webrtc) project running.
Unfortunately, I'm facing the same problem (as I issued [here](https://github.com/cjb/serverless-webrtc/issues/31)). It works well in a local environment, but as soon as I try it in the public network it fails. 
I'm getting the error message `ICE failed, add a TURN server and see about:webrtc for more details`.

I've tried the following steps, which worked well in local network:
1. clicked 'BOB: Create' button in browser 1
2. clicked 'ALICE: Join' button in browser 2
3. pasted 'BOB: Send your local offer to ALICE' string from browser 1 in 'ALICE: Paste the "offer" you received' field in browser 2
4. clicked 'Okay, I pasted it' button.
5. pasted 'Then, send your local answer to BOB' string from browser 2 in 'Then, paste the "answer" you received' field in browser 1
6. clicked 'Okay, I pasted it' button.

I used two Firefox browser in version 54.0 on two Ubuntu 16.04 systems.
In contrast to the serverless-webrtc project, the offer and answer strings contain the public IP addresses.

I think the problem now is not to get the public IP addresses, but to establish a connecting with the ice protocol, which is one step further.

Do you have any recommendations or advice to finally get a connection established?

Thanks in advance.

**Comment by xem** [comment]
Hi! Thanks for your message.
All I did here is to fork a version of serverless-webrtc that worked fine and simplify it as much as I could.
I've tried it online successfully with different people that were in foreign countries and it worked fine, except when the other person was on Linux+Firefox.
I have no idea what happened, it may not be related to Firefox or Linux, and could be related to network details (VPN, firewall, ipv6 router, isp?).
Have you tried on Chrome?

**Comment by Stupid-Git** [comment]
Just a comment really.   
I ran index.html in two tabs on one machine (Debian 9 Native, Firefox 52.5.0); all OK.   
On another network on a VirtualBox machine (Debian 9, Firefox 52.5.0); No luck between two tabs, and of course no luck between the two machines.   
I then noticed that I had the "Copper" (Coap Client) Add-On installed on the Browser of the first machine.   
Installing the same Add-On onto the Virtual machines Browser brought everything to life.   
Incidentally, I had successfully communicated between the two machines with the Konsole version of your reference project  [https://github.com/cjb/serverless-webrtc/pull/27/files](https://github.com/cjb/serverless-webrtc/pull/27/files)  so I am pretty sure it is only a Firefox Browser issue.   
If anyone could explain what is being activated in this case, please share your views.   
Thanks.  Karel
